config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls', namespace='post')),
    path('contact/', include('contact.urls', namespace='contact')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.urls import path
from .views import *

app_name = 'contact'

urlpatterns = [
    path('', contact, name='contact'),
    path('about/', about, name='about'),
]

post/urls.py
from django.urls import path
from .views import *

app_name = 'post'

urlpatterns = [
    path('', home, name='home'),
    path('blog-single/<int:pk>/', blog_single, name='blog-single'),
    path('fashion/', fashion, name='fashion'),
    path('travel/', travel, name='travel'),
]

contact/models.py
from django.db import models


# Create your models here.


class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Subscribe(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email

post/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

TYPE = (
    (0, 'Fashion'),
    (1, 'Travel'),
)


class Category(models.Model):
    category = models.CharField(max_length=255)

    def __str__(self):
        return self.category


class Tag(models.Model):
    tag = models.CharField(max_length=255)

    def __str__(self):
        return self.tag


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    type = models.IntegerField(choices=TYPE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='posts')
    views = models.IntegerField(default=0)
    tags = models.ManyToManyField(Tag, blank=True)
    content = models.TextField()
    author_name = models.CharField(max_length=255)
    avatar = models.ImageField(upload_to='author')
    author_commit = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    avatar = models.ImageField(upload_to='comment', null=True, blank=True)
    website = models.URLField(null=True, blank=True)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

contact/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field_name.capitalize()

post/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'
        exclude = ['post']

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field_name.capitalize()

contact/views.py
from django.shortcuts import render
from .forms import ContactForm
from .models import *


# Create your views here.


def contact(request):
    form = ContactForm(request.POST or None)
    if form.is_valid():
        form.save()
    email = request.GET.get('email')
    if email:
        Subscribe.objects.create(email=email)
    ctx = {
        'form': form
    }
    return render(request, 'contact.html', ctx)


def about(request):
    email = request.GET.get('email')
    if email:
        Subscribe.objects.create(email=email)
    return render(request, 'about.html')

post/views.py
from django.shortcuts import render
from .models import *
from contact.models import Subscribe
from .forms import CommentForm


# Create your views here.

def home(request):
    posts = Post.objects.order_by('-id')
    s = request.GET.get('s')
    if s:
        posts = posts.filter(title__icontains=s)
    t = request.GET.get('t')
    if t:
        posts = posts.filter(tags__tag__exact=t)
    c = request.GET.get('c')
    if c:
        posts = posts.filter(category__category__exact=c)
    email = request.GET.get('email')
    if email:
        Subscribe.objects.create(email=email)
    ctx = {
        'posts': posts
    }
    return render(request, 'index.html', ctx)


def blog_single(request, pk):
    post = Post.objects.get(id=pk)
    post.views += 1
    post.save()
    form = CommentForm(request.POST or None, request.FILES)
    if form.is_valid():
        commit = form.save(commit=False)
        commit.post = post
        commit.save()

    ctx = {
        'post': post,
        'form': form,
    }
    return render(request, 'single.html', ctx)


def fashion(request):
    posts = Post.objects.filter(type=0)
    ctx = {
        'posts': posts
    }
    return render(request, 'fashion.html', ctx)


def travel(request):
    posts = Post.objects.filter(type=1)
    q = request.GET.get('q')
    if q:
        posts = Post.objects.filter(author_name=q)
    ctx = {
        'posts': posts
    }
    return render(request, 'travel.html', ctx)

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div id="colorlib-main">
        <section class="ftco-about img ftco-section ftco-no-pt ftco-no-pb" id="about-section">
            <div class="container-fluid px-0">
                <div class="row d-flex">
                    <div class="col-md-6 d-flex">
                        <div class="img d-flex align-self-stretch align-items-center js-fullheight"
                             style="background-image:url({% static 'images/Me.jpg' %});">
                        </div>
                    </div>
                    <div class="col-md-6 d-flex align-items-center">
                        <div class="text px-4 pt-5 pt-md-0 px-md-4 pr-md-5 ftco-animate">
                            <h2 class="mb-4">I'm <span>Ravshan Giyosov</span> a Scotish Blogger &amp; Explorer</h2>
                            <p>A small river named Duden flows by their place and supplies it with the necessary
                                regelialia. It is a paradisematic country, in which roasted parts of sentences fly into
                                your mouth. It is a paradisematic country, in which roasted parts of sentences fly into
                                your mouth.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Andrea - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&amp;display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet"
          href="{% static 'css/A.open-iconic-bootstrap.min.css+animate.css+owl.carousel.min.css+owl.theme.default.min.css+magnific-popup.css+aos.css+ionicons.min.css+bootstrap-datepicker.css+jquery.timepicker.css+flaticon.css' %}"/>
    <script nonce="0ad9716a-9ec3-4298-bd62-9f4df4bb5bd6">(function (w, d) {
        !function (a, e, t, r) {
            a.zarazData = a.zarazData || {}, a.zarazData.executed = [], a.zaraz = {deferred: []}, a.zaraz.q = [], a.zaraz._f = function (e) {
                return function () {
                    var t = Array.prototype.slice.call(arguments);
                    a.zaraz.q.push({m: e, a: t})
                }
            };
            for (const e of ["track", "set", "ecommerce", "debug"]) a.zaraz[e] = a.zaraz._f(e);
            a.addEventListener("DOMContentLoaded", (() => {
                var t = e.getElementsByTagName(r)[0], z = e.createElement(r), n = e.getElementsByTagName("title")[0];
                for (n && (a.zarazData.t = e.getElementsByTagName("title")[0].text), a.zarazData.x = Math.random(), a.zarazData.w = a.screen.width, a.zarazData.h = a.screen.height, a.zarazData.j = a.innerHeight, a.zarazData.e = a.innerWidth, a.zarazData.l = a.location.href, a.zarazData.r = e.referrer, a.zarazData.k = a.screen.colorDepth, a.zarazData.n = e.characterSet, a.zarazData.o = (new Date).getTimezoneOffset(), a.zarazData.q = []; a.zaraz.q.length;) {
                    const e = a.zaraz.q.shift();
                    a.zarazData.q.push(e)
                }
                z.defer = !0;
                for (const e of [localStorage, sessionStorage]) Object.keys(e).filter((a => a.startsWith("_zaraz_"))).forEach((t => {
                    try {
                        a.zarazData["z_" + t.slice(7)] = JSON.parse(e.getItem(t))
                    } catch {
                        a.zarazData["z_" + t.slice(7)] = e.getItem(t)
                    }
                }));
                z.referrerPolicy = "origin", z.src = "https://preview.colorlib.com/cdn-cgi/zaraz/s.js?z=" + btoa(encodeURIComponent(JSON.stringify(a.zarazData))), t.parentNode.insertBefore(z, t)
            }))
        }(w, d, 0, "script");
    })(window, document);</script>
</head>
<body>
<div id="colorlib-page">
    <a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>
    <aside id="colorlib-aside" role="complementary" class="js-fullheight">
        <nav id="colorlib-main-menu" role="navigation">
            <ul>
                <li class="colorlib-active"><a href="/">Home</a></li>
                <li><a href="{% url 'post:fashion' %}">Fashion</a></li>
                <li><a href="{% url 'post:travel' %}">Travel</a></li>
                <li><a href="{% url 'contact:about' %}">About</a></li>
                <li><a href="{% url 'contact:contact' %}">Contact</a></li>
            </ul>
        </nav>
        <div class="colorlib-footer">
            <h1 id="colorlib-logo" class="mb-4"><a href="/" style="background-image:url({% static 'images/xbg_1.jpg.pagespeed.ic.yyDakF8d8Y.jpg' %})">Ravshan
                <span>Giyosov</span></a></h1>
            <div class="mb-4">
                <h3>Subscribe for newsletter</h3>
                <form method="get" class="colorlib-subscribe-form">
                    <div class="form-group d-flex">
                        <div class="icon"><span class="icon-paper-plane"></span></div>
                        <input type="email" name="email" class="form-control" placeholder="Enter Email Address">
                    </div>
                </form>
            </div>
            <p class="pfooter">
                Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a
                    href="https://colorlib.com/" target="_blank">Colorlib</a>
            </p>
        </div>
    </aside>

    {% block content %}

    {% endblock %}
</div>

<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
</div>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.1.min.js+popper.min.js+bootstrap.min.js.pagespeed.jc.ufA-InWYhU.js' %}"></script>
<script>eval(mod_pagespeed_j9z0BOW3Xo);</script>
<script>eval(mod_pagespeed_Sv59xs6XfY);</script>
<script>eval(mod_pagespeed_6hivBMilT4);</script>
<script src="{% static 'js/jquery.easing.1.3.js+jquery.waypoints.min.js+jquery.stellar.min.js+owl.carousel.min.js.pagespeed.jc.7Uf8nwPPt3.js' %}"></script>
<script>eval(mod_pagespeed_a9in6ca9LP);</script>
<script>eval(mod_pagespeed_E5Rl_eUdra);</script>
<script>eval(mod_pagespeed_J7fR9gg3IV);</script>
<script>eval(mod_pagespeed_JGC9XV$UWo);</script>
<script src="{% static 'js/jquery.magnific-popup.min.js+aos.js+jquery.animateNumber.min.js+scrollax.min.js+google-map.js+main.js.pagespeed.jc.noK85cOv9x.js' %}"></script>
<script>eval(mod_pagespeed_9FDixMCPbL);</script>
<script>eval(mod_pagespeed_cWDp1F0K9O);</script>
<script>eval(mod_pagespeed_tBed9FYmsP);</script>
<script>eval(mod_pagespeed_xipmmYMCNr);</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&amp;sensor=false"></script>
<script>eval(mod_pagespeed_YuUFcjXVeT);</script>
<script>eval(mod_pagespeed_6pY$MsZg3C);</script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'UA-23581568-13');
</script>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194"
        integrity="sha512-Gi7xpJR8tSkrpF7aordPZQlW2DLtzUlZcumS8dMQjwDHEnw9I7ZLyiOj/6tZStRBGtGgN6ceN6cMH8z7etPGlw=="
        data-cf-beacon='{"rayId":"7169494d5d752398","token":"cd0b4b3a733644fc843ef0b185f98241","version":"2021.12.0","si":100}'
        crossorigin="anonymous"></script>
</body>
</html>

templates/fashion.html
{% extends 'base.html' %}

{% block content %}

    <div id="colorlib-main">
        <section class="ftco-section">
            <div class="container">
                <div class="row px-md-4">
                    {% for post in posts %}
                        <div class="col-md-12">
                        <div class="blog-entry ftco-animate d-md-flex">
                            <a href="{% url 'post:blog-single' post.id %}" class="img img-2"
                               style="background-image:url({{ post.image.url }})"></a>
                            <div class="text text-2 pl-md-4">
                                <h3 class="mb-2"><a href="{% url 'post:blog-single' post.id %}">{{ post.title|slice:'150' }}</a></h3>
                                <div class="meta-wrap">
                                    <p class="meta">
                                        <span><i class="icon-calendar mr-2"></i>{{ post.created_at }}</span>
                                        <span><a href="single.html"><i class="icon-folder-o mr-2"></i>{{ post.category }}</a></span>
                                        <span><i class="icon-comment2 mr-2"></i>{{ post.comment_set.count }} Comment</span>
                                    </p>
                                </div>
                                <p class="mb-4">{{ post.content|slice:'170' }}</p>
                                <p><a href="{% url 'post:blog-single' post.id %}" class="btn-custom">Read More <span class="ion-ios-arrow-forward"></span></a>
                                </p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="row">
                    <div class="col text-center text-md-left">
                        <div class="block-27">
                            <ul>
                                <li><a href="#">&lt;</a></li>
                                <li class="active"><span>1</span></li>
                                <li><a href="#">2</a></li>
                                <li><a href="#">3</a></li>
                                <li><a href="#">4</a></li>
                                <li><a href="#">5</a></li>
                                <li><a href="#">&gt;</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}

    <div id="colorlib-main">
        <section class="ftco-section ftco-no-pt ftco-no-pb">
            <div class="container">
                <div class="row d-flex">
                    <div class="col-xl-8 py-5 px-md-5">
                        <div class="row pt-md-4">
                            {% for post in posts %}
                                <div class="col-md-12">
                                <div class="blog-entry ftco-animate d-md-flex">
                                    <a href="{% url 'post:blog-single' post.id %}" class="img img-2"
                                       style="background-image:url({{ post.image.url }})"></a>
                                    <div class="text text-2 pl-md-4">
                                        <h3 class="mb-2"><a href="{% url 'post:blog-single' post.id %}">{{ post.title|slice:'100'}}</a></h3>
                                        <div class="meta-wrap">
                                            <p class="meta">
                                                <span><i class="icon-calendar mr-2"></i>{{ post.created_at|date:'F' }} {{ post.created_at|date:'d' }} {{ post.created_at|date:'Y' }}</span>
                                                <span><a href="/?c={{ post.category.category }}"><i class="icon-folder-o mr-2"></i>{{ post.category }}</a></span>
                                                <span><i class="icon-comment2 mr-2"></i>{{ post.comment_set.count }} Comment</span>
                                            </p>
                                        </div>
                                        <p class="mb-4">{{ post.content|slice:'170'}}</p>
                                        <p><a href="{% url 'post:blog-single' post.id %}" class="btn-custom">Read More <span
                                                class="ion-ios-arrow-forward"></span></a></p>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        <div class="row">
                            <div class="col">
                                <div class="block-27">
                                    <ul>
                                        <li><a href="#">&lt;</a></li>
                                        <li class="active"><span>1</span></li>
                                        <li><a href="#">2</a></li>
                                        <li><a href="#">3</a></li>
                                        <li><a href="#">4</a></li>
                                        <li><a href="#">5</a></li>
                                        <li><a href="#">&gt;</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% include 'rsidbar.html' %}
                </div>
            </div>
        </section>
    </div>

{% endblock %}

templates/rsidbar.html
{% load static %}
{% load last_posts %}
{% last_posts as last_posts%}
{% categories as categories%}
{% tags as tags %}

<div class="col-xl-4 sidebar ftco-animate bg-light pt-5">
    <div class="sidebar-box pt-md-4">
        <form method="get" action="/" class="search-form">
            <div class="form-group">
                <span class="icon icon-search"></span>
                <input type="search" name="s" class="form-control" placeholder="Type a keyword and hit enter">
            </div>
        </form>
    </div>
    <div class="sidebar-box ftco-animate">
        <h3 class="sidebar-heading">Categories</h3>
        <ul class="categories">
            {% for category in categories %}
                <li><a href="/?c={{ category }}">{{ category.category }} <span>({{ category.post_set.count }})</span></a></li>
            {% endfor %}
        </ul>
    </div>
    <div class="sidebar-box ftco-animate">
        <h3 class="sidebar-heading">Popular Articles</h3>
        {% for last_post in last_posts %}
            <div class="block-21 mb-4 d-flex">
            <a class="blog-img mr-4"
               style="background-image:url({{ last_post.image.url }})"></a>
            <div class="text">
                <h3 class="heading"><a href="{% url 'post:blog-single' last_post.id %}">{{ last_post.title|slice:'100'}}</a></h3>
                <div class="meta">
                    <div><span class="icon-calendar"></span> {{ last_post.created_at|date:'F' }} {{ last_post.created_at|date:'d' }} {{ last_post.created_at|date:'Y' }}</div>
                    <div><span class="icon-person"></span> {{ last_post.author_name }}</div>
                    <div><span class="icon-chat"></span> {{ last_post.comment_set.count }}</div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="sidebar-box ftco-animate">
        <h3 class="sidebar-heading">Tag Cloud</h3>
        <ul class="tagcloud">
            {% for tag in tags %}
                <a href="/?t={{ tag }}" class="tag-cloud-link">{{ tag.tag }}</a>
            {% endfor %}
        </ul>
    </div>
    <div class="sidebar-box subs-wrap img py-4"
         style="background-image:url({% static 'images/xbg_1.jpg.pagespeed.ic.yyDakF8d8Y.jpg' %})">
        <div class="overlay"></div>
        <h3 class="mb-4 sidebar-heading">Newsletter</h3>
        <p class="mb-4">Far far away, behind the word mountains, far from the countries Vokalia</p>
        <form method="get" class="subscribe-form">
            <div class="form-group">
                <input type="email" name="email" class="form-control" placeholder="Email Address">
                <input type="submit" value="Subscribe" class="mt-2 btn btn-white submit">
            </div>
        </form>
    </div>
    <div class="sidebar-box ftco-animate">
        <h3 class="sidebar-heading">Paragraph</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem
            necessitatibus voluptate quod mollitia delectus aut.</p>
    </div>
</div>

templates/single.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div id="colorlib-main">
        <section class="ftco-section ftco-no-pt ftco-no-pb">
            <div class="container">
                <div class="row d-flex">
                    <div class="col-lg-8 px-md-5 py-5">
                        <div class="row pt-md-4">
                            <h1 class="mb-3">{{ post.title }}</h1>
                            <p>
                                <img src="{{ post.image.url }}" alt="" class="img-fluid">
                            </p>
                            <p>{{ post.content }}</p>
                            <div class="tag-widget post-tag-container mb-5 mt-5">
                                <div class="tagcloud">
                                    {% for tag in post.tags.all %}
                                        <a class="tag-cloud-link">{{ tag }}</a>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="about-author d-flex p-4 bg-light">
                                <div class="bio mr-5">
                                    <img src="{{ post.avatar.url }}" alt="Image placeholder"
                                         class="img-fluid mb-4">
                                </div>
                                <div class="desc">
                                    <h3>{{ post.author_name }}</h3>
                                    <p>{{ post.author_commit }}</p>
                                </div>
                            </div>
                            <div class="pt-5 mt-5">
                                <h3 class="mb-5 font-weight-bold">{{ post.comment_set.count }} Comments</h3>
                                <ul class="comment-list">
                                    {% for comment in post.comment_set.all %}
                                        <li class="comment">
                                        <div class="vcard bio">
                                            {% if comment.avatar %}
                                                <img src="{{ comment.avatar.url }}" alt="Image placeholder">
                                            {% else %}
                                                <img src="{% static 'images/user.jpg' %}" alt="Image placeholder">
                                            {% endif %}
                                        </div>
                                        <div class="comment-body">
                                            <h3>{{ comment.name }}</h3>
                                            <div class="meta">{{ comment.created_at }}</div>
                                            <p>{{ comment.message }}</p>
                                        </div>
                                    </li>
                                    {% endfor %}
                                </ul>
                                <div class="comment-form-wrap pt-5">
                                    <h3 class="mb-5">Leave a comment</h3>
                                    <form method="post" class="p-3 p-md-5 bg-light" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <label for="name">Name *</label>
                                            {{ form.name }}
                                        </div>
                                        <div class="form-group">
                                            <label for="email">Email *</label>
                                            {{ form.email }}
                                        </div>
                                        <div class="form-group">
                                            <label for="image">Image</label>
                                            {{ form.avatar }}
                                        </div>
                                        <div class="form-group">
                                            <label for="website">Website</label>
                                            {{ form.website }}
                                        </div>
                                        <div class="form-group">
                                            <label for="message">Message</label>
                                            {{ form.message }}
                                        </div>
                                        <div class="form-group">
                                            <input type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% include 'rsidbar.html' %}
                </div>
            </div>
        </section>
    </div>

{% endblock %}

templates/travel.html
{% extends 'base.html' %}

{% block content %}

    <div id="colorlib-main">
        <section class="ftco-section ftco-no-pt ftco-no-pb">
            <div class="container">
                <div class="row d-flex">
                    <div class="col-xl-8 px-md-5 py-5">
                        <div class="row pt-md-4">
                            {% for post in posts %}
                                <div class="col-md-12">
                                <div class="blog-entry-2 ftco-animate">
                                    <a href="{% url 'post:blog-single' post.id %}" class="img"
                                       style="background-image:url({{ post.image.url }})"></a>
                                    <div class="text pt-4">
                                        <h3 class="mb-4"><a href="{% url 'post:blog-single' post.id %}">{{ post.title|slice:'100' }}</a></h3>
                                        <p class="mb-4">{{ post.content|slice:'170' }}</p>
                                        <div class="author mb-4 d-flex align-items-center">
                                            <a class="img" style="background-image:url({{ post.avatar.url }})"></a>
                                            <div class="ml-3 info">
                                                <span>Written by</span>
                                                <h3><a href="?q={{ post.author_name }}">{{ post.author_name }}</a>, <span>{{ post.created_at }}</span></h3>
                                            </div>
                                        </div>
                                        <div class="meta-wrap d-md-flex align-items-center">
                                            <div class="half order-md-last text-md-right">
                                                <p class="meta">
                                                    <span><i class="icon-eye"></i>{{ post.views }}</span>
                                                    <span><i class="icon-comment"></i>{{ post.comment_set.count }}</span>
                                                </p>
                                            </div>
                                            <div class="half">
                                                <p><a href="{% url 'post:blog-single' post.id %}" class="btn btn-primary p-3 px-xl-4 py-xl-3">Continue
                                                    Reading</a></p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        <div class="row">
                            <div class="col">
                                <div class="block-27">
                                    <ul>
                                        <li><a href="#">&lt;</a></li>
                                        <li class="active"><span>1</span></li>
                                        <li><a href="#">2</a></li>
                                        <li><a href="#">3</a></li>
                                        <li><a href="#">4</a></li>
                                        <li><a href="#">5</a></li>
                                        <li><a href="#">&gt;</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% include 'rsidbar.html' %}
                </div>
            </div>
        </section>
    </div>

{% endblock %}